import { chromium } from "playwright";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import sharp from "sharp";
import { createHash } from "node:crypto";

const url = process.env.PREVIEW_URL || "http://127.0.0.1:4176/";
const site = process.env.EXPECTED_SITE_URL || "https://wedding.moreda.me/";
const asset = "assets/share/wedding-cover-976137ba.jpg";
const title = "毛凌涛 & 陈婉梦 · 婚礼请柬";
const description = "2026.10.22 — 10.23 · Garden Wedding → Stardew Autumn Party";
const localImage = await readFile(`public/${asset}`);
assert.equal(createHash("sha256").update(localImage).digest("hex").slice(0, 8), "976137ba");
assert.deepEqual(localImage, await readFile("public/assets/share/wedding-cover.jpg"));
const info = await sharp(localImage).metadata();
assert.equal(info.width, 1200);
assert.equal(info.height, 630);
assert.ok(!info.exif && !info.xmp);
assert.ok(localImage.length >= 200 * 1024 && localImage.length <= 500 * 1024);
const browser = await chromium.launch({ executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" });
try {
  const page = await browser.newPage({ javaScriptEnabled: false });
  const response = await page.goto(url, { waitUntil: "networkidle" });
  const html = await response.text();
  assert.ok(!html.includes("__PUBLIC_SITE_URL__"), "Metadata is resolved at build time");
  const meta = key => page.locator(`meta[property="${key}"]`).getAttribute("content");
  assert.equal(await page.title(), title);
  assert.equal(await meta("og:title"), title);
  assert.equal(await meta("og:description"), description);
  assert.equal(await meta("og:type"), "website");
  assert.equal(await meta("og:url"), site);
  assert.equal(await meta("og:image"), `${site}${asset}`);
  assert.equal(await meta("og:image:secure_url"), `${site}${asset}`);
  assert.equal(await meta("og:locale"), "zh_CN");
  assert.equal(await meta("og:site_name"), "M & M Wedding");
  assert.equal(await meta("og:image:type"), "image/jpeg");
  assert.equal(await meta("og:image:width"), "1200");
  assert.equal(await meta("og:image:height"), "630");
  assert.ok(await meta("og:image:alt"));
  assert.equal(await page.locator('link[rel="canonical"]').getAttribute("href"), site);
  assert.equal(await page.locator('meta[name="twitter:image"]').getAttribute("content"), `${site}${asset}`);
  assert.equal(await page.locator('meta[name="twitter:title"]').getAttribute("content"), title);
  assert.equal(await page.locator('meta[name="twitter:description"]').getAttribute("content"), description);
  assert.equal(await page.locator('meta[name="twitter:card"]').getAttribute("content"), "summary_large_image");
  assert.equal(await page.locator('meta[name="description"]').getAttribute("content"), "2026.10.22 — 10.23 · 想请你来参加我们的婚礼。");
  const cover = await page.request.get(new URL(asset, url).href);
  assert.equal(cover.status(), 200);
  assert.match(cover.headers()["content-type"], /image\/jpeg/);
  assert.deepEqual(await cover.body(), localImage);
  const alias = await page.request.get(new URL("assets/share/wedding-cover.jpg", url).href);
  assert.equal(alias.status(), 200);
  assert.match(alias.headers()["content-type"], /image\/jpeg/);
  assert.deepEqual(await alias.body(), localImage);
  await page.close();

  const app = await browser.newPage({ viewport: { width: 390, height: 844 } });
  const covers = [];
  app.on("request", request => { if (request.url().includes("/assets/share/")) covers.push(request.url()); });
  await app.goto(url, { waitUntil: "networkidle" });
  assert.equal(await app.locator('body img[src*="/assets/share/"]').count(), 0);
  assert.equal(covers.length, 0, "Share-only artwork must not cost bandwidth in the invitation");
  assert.equal(await app.locator(".invitation").getAttribute("data-audio-status"), "off");
  console.log("Share metadata passed without JavaScript; full-composition JPEG loads correctly, has no EXIF and never appears or loads in the invitation");
} finally { await browser.close(); }
